from .nodes import *
from .gguf_nodes import WarpedLoaderGGUF, WarpedClipLoaderGGUF, WarpedDualClipLoaderGGUF

NODE_CLASS_MAPPINGS = {
    "WarpedHunyuanMultiLoraMerge": WarpedHunyuanMultiLoraMerge,
    "WarpedHunyuanMultiLoraAvgMerge": WarpedHunyuanMultiLoraAvgMerge,
    "WarpedHunyuanLoraMerge": WarpedHunyuanLoraMerge,
    "WarpedHunyuanMultiLoraMixer": WarpedHunyuanMultiLoraMixer,
    "WarpedHunyuanMultiLoraMixerExt": WarpedHunyuanMultiLoraMixerExt,
    "WarpedHunyuanLoraAvgMerge": WarpedHunyuanLoraAvgMerge,
    "WarpedHunyuanLoraBatchMerge": WarpedHunyuanLoraBatchMerge,
    "WarpedWanLoraMerge": WarpedWanLoraMerge,
    "WarpedSamplerCustomAdv": WarpedSamplerCustomAdv,
    "WarpedSamplerCustomAdvLatent": WarpedSamplerCustomAdvLatent,
    "WarpedSamplerCustomScripted": WarpedSamplerCustomScripted,
    "WarpedFramepackSampler": WarpedFramepackSampler,
    # "WarpedFramepackSamplerScripted": WarpedFramepackSamplerScripted,
    "WarpedCreateSpecialImageBatch": WarpedCreateSpecialImageBatch,
    "WarpedCreateEmptyImageBatch": WarpedCreateEmptyImageBatch,
    "WarpedCreateEmptyLatentBatch": WarpedCreateEmptyLatentBatch,
    "WarpedBundleVideoImages": WarpedBundleVideoImages,
    "WarpedBundleAllVideoImages": WarpedBundleAllVideoImages,
    "WarpedGetImageFromVideo": WarpedGetImageFromVideo,
    "WarpedGetTwoImagesFromVideo": WarpedGetTwoImagesFromVideo,
    "WarpedImageNoiseAugmentation": WarpedImageNoiseAugmentation,
    "WarpedLeapfusionHunyuanI2V": WarpedLeapfusionHunyuanI2V,
    "WarpedSaveAnimatedPng": WarpedSaveAnimatedPng,
    "WarpedUpscaleWithModel": WarpedUpscaleWithModel,
    "WarpedLoadVideosBatch": WarpedLoadVideosBatch,
    "WarpedWanImageToVideo": WarpedWanImageToVideo,
    "WarpedWanLoadAndEditLoraBlocks": WarpedWanLoadAndEditLoraBlocks,
    "WarpedImageScaleToSide": WarpedImageScaleToSide,
    "WarpedLoadLorasBatchByPrefix": WarpedLoadLorasBatchByPrefix,
    "WarpedHunyuanVideoLoraLoader": WarpedHunyuanVideoLoraLoader,
    "WarpedHunyuanMultiLoraLoader": WarpedHunyuanMultiLoraLoader,
    "WarpedHunyuanLoraConvertKeys": WarpedHunyuanLoraConvertKeys,
    # "WarpedHunyuanLoraConvertKeys2": WarpedHunyuanLoraConvertKeys2,
    "WarpedLoraKeysAndMetadataReader": WarpedLoraKeysAndMetadataReader,
    "WarpedHunyuanLoraConvert": WarpedHunyuanLoraConvert,
    "WarpedFramepackLoraSelectBatch": WarpedFramepackLoraSelectBatch,
    "WarpedFramepackMultiLoraSelect": WarpedFramepackMultiLoraSelect,
    "WarpedFramepackMultiLoraSelectExt": WarpedFramepackMultiLoraSelectExt,
    "WarpedCLIPLoader": WarpedCLIPLoader,
    "WarpedDualCLIPLoader": WarpedDualCLIPLoader,
    "WarpedDualEncoder": WarpedDualEncoder,
    "WarpedCLIPVisionLoader": WarpedCLIPVisionLoader,
    "WarpedVAELoader": WarpedVAELoader,
    "WarpedLoadFramePackModel": WarpedLoadFramePackModel,
    "WarpedNumericalConversion": WarpedNumericalConversion,
    "WarpedLoraReSave": WarpedLoraReSave,
    "WarpedCheckpointLoader": WarpedCheckpointLoader,
    "WarpedReverseImageBatch": WarpedReverseImageBatch,
    "WarpedMultiLoraLoader": WarpedMultiLoraLoader,
    "WarpedHunyuanImageToVideo": WarpedHunyuanImageToVideo,
    "WarpedBasicGuider": WarpedBasicGuider,
    "WarpedDualGuider": WarpedDualGuider,
    "WarpedLoaderGGUF": WarpedLoaderGGUF,
    "WarpedClipLoaderGGUF": WarpedClipLoaderGGUF,
    "WarpedDualClipLoaderGGUF": WarpedDualClipLoaderGGUF,
    "WarpedSamplerScripts5": WarpedSamplerScripts5,
    "WarpedSamplerScripts8": WarpedSamplerScripts8,
    "WarpedSamplerScripts12": WarpedSamplerScripts12,
    "WarpedSamplerScripts16": WarpedSamplerScripts16,
    "WarpedSamplerScripts20": WarpedSamplerScripts20,
    "WarpedSamplerScripts30": WarpedSamplerScripts30,
    "WarpedSamplerScripts40": WarpedSamplerScripts40,
    "WarpedLoadImages": WarpedLoadImages,
    "WarpedSaveImageCaption": WarpedSaveImageCaption,
    "WarpedModifyCaptionFile": WarpedModifyCaptionFile,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "WarpedHunyuanMultiLoraMerge": "Warped Hunyuan Multi Lora Merge",
    "WarpedHunyuanMultiLoraAvgMerge": "Warped Hunyuan Multi Lora Avg Merge",
    "WarpedHunyuanLoraMerge": "Warped Hunyuan Lora Merge",
    "WarpedHunyuanMultiLoraMixer": "Warped Hunyuan Multi Lora Mixer",
    "WarpedHunyuanMultiLoraMixerExt": "Warped Hunyuan Multi Lora Mixer Ext",
    "WarpedHunyuanLoraAvgMerge": "Warped Hunyuan Lora Avg Merge",
    "WarpedHunyuanLoraBatchMerge": "Warped Hunyuan Lora Batch Merge",
    "WarpedWanLoraMerge": "Warped Wan Lora Merge",
    "WarpedSamplerCustomAdv": "Warped Sampler Custom Advanced (Image)",
    "WarpedSamplerCustomAdvLatent": "Warped Sampler Custom Advanced (Latent)",
    "WarpedSamplerCustomScripted": "Warped Sampler Custom Scripted",
    "WarpedFramepackSampler": "Warped Framepack Sampler",
    # "WarpedFramepackSamplerScripted": "Warped Framepack Sampler Scripted",
    "WarpedCreateSpecialImageBatch": "Warped Create Special Image Batch",
    "WarpedCreateEmptyImageBatch": "Warped Create Empty Image Batch",
    "WarpedCreateEmptyLatentBatch": "Warped Create Empty Latent Batch",
    "WarpedBundleVideoImages": "Warped Bundle Video Images",
    "WarpedBundleAllVideoImages": "Warped Bundle All Video Images",
    "WarpedGetImageFromVideo": "Warped Get Image From Video",
    "WarpedGetTwoImagesFromVideo": "Warped Get Two Images From Video",
    "WarpedImageNoiseAugmentation": "Warped Image Noise Augmentation",
    "WarpedLeapfusionHunyuanI2V": "Warped Leapfusion Hunyuan I2V",
    "WarpedSaveAnimatedPng": "Warped Save Animated Png",
    "WarpedUpscaleWithModel": "Warped Upscale With Model",
    "WarpedLoadVideosBatch": "Warped Load Videos Batch",
    "WarpedWanImageToVideo": "Warped Wan Image To Video",
    "WarpedWanLoadAndEditLoraBlocks": "Warped Wan Load And Edit Lora Blocks",
    "WarpedImageScaleToSide": "Warped Image Scale To Side",
    "WarpedLoadLorasBatchByPrefix": "Warped Load Loras Batch By Prefix",
    "WarpedHunyuanVideoLoraLoader": "Warped Hunyuan Video Lora Loader",
    "WarpedHunyuanMultiLoraLoader": "Warped Hunyuan Video Multi Lora Loader",
    "WarpedHunyuanLoraConvertKeys": "Warped Hunyuan Lora Convert Keys",
    # "WarpedHunyuanLoraConvertKeys2": "Warped Hunyuan Lora Convert Keys 2",
    "WarpedLoraKeysAndMetadataReader": "Warped Lora Keys And Metadata Reader",
    "WarpedHunyuanLoraConvert": "Warped Hunyuan Lora Convert",
    "WarpedFramepackLoraSelectBatch": "Warped Framepack Lora Select Batch",
    "WarpedFramepackMultiLoraSelect": "Warped Framepack Multi Lora Select",
    "WarpedFramepackMultiLoraSelectExt": "Warped Framepack Multi Lora Select Ext",
    "WarpedCLIPLoader": "Warped CLIP Loader",
    "WarpedDualCLIPLoader": "Warped Dual CLIP Loader",
    "WarpedDualEncoder": "Warped Dual Encoder",
    "WarpedCLIPVisionLoader": "Warped Load CLIP Vision",
    "WarpedVAELoader": "Warped Load VAE",
    "WarpedLoadFramePackModel": "Warped Load FramePack Model",
    "WarpedNumericalConversion": "Warped Numerical Conversion",
    "WarpedLoraReSave": "Warped Lora Re-Save",
    "WarpedCheckpointLoader": "Warped Checkpoint Loader",
    "WarpedReverseImageBatch": "Warped Reverse Image Batch",
    "WarpedMultiLoraLoader": "Warped Multi Lora Loader",
    "WarpedHunyuanImageToVideo": "Warped Hunyuan Image To Video",
    "WarpedBasicGuider": "Warped Basic Guider Batch",
    "WarpedDualGuider": "Warped Dual Guider",
    "WarpedLoaderGGUF": "Warped UNET Loader GGUF",
    "WarpedClipLoaderGGUF": "Warped Clip Loader GGUF",
    "WarpedDualClipLoaderGGUF": "Warped Dual Clip Loader GGUF",
    "WarpedSamplerScripts5": "Warped Sampler Scripts 5",
    "WarpedSamplerScripts8": "Warped Sampler Scripts 8",
    "WarpedSamplerScripts12": "Warped Sampler Scripts 12",
    "WarpedSamplerScripts16": "Warped Sampler Scripts 16",
    "WarpedSamplerScripts20": "Warped Sampler Scripts 20",
    "WarpedSamplerScripts30": "Warped Sampler Scripts 30",
    "WarpedSamplerScripts40": "Warped Sampler Scripts 40",
    "WarpedLoadImages": "Warped Load Images",
    "WarpedSaveImageCaption": "Warped Save Image Caption",
    "WarpedModifyCaptionFile": "Warped Modify Caption File",
}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
