from .nodes import *

NODE_CLASS_MAPPINGS = {
    "WarpedHunyuanMultiLoraMerge": WarpedHunyuanMultiLoraMerge,
    "WarpedHunyuanMultiLoraAvgMerge": WarpedHunyuanMultiLoraAvgMerge,
    "WarpedHunyuanLoraMerge": WarpedHunyuanLoraMerge,
    # "WarpedHunyuanLoraMergeExp": WarpedHunyuanLoraMergeExp,
    # "WarpedHunyuanConvert32To64Exp": WarpedHunyuanConvert32To64Exp,
    "WarpedHunyuanLoraAvgMerge": WarpedHunyuanLoraAvgMerge,
    "WarpedWanLoraMerge": WarpedWanLoraMerge,
    "WarpedSamplerCustomAdv": WarpedSamplerCustomAdv,
    "WarpedSamplerCustomAdvLatent": WarpedSamplerCustomAdvLatent,
    "WarpedCreateSpecialImageBatch": WarpedCreateSpecialImageBatch,
    # "WarpedCreateSpecialImageBatchExt": WarpedCreateSpecialImageBatchExt,
    "WarpedCreateEmptyImageBatch": WarpedCreateEmptyImageBatch,
    "WarpedBundleVideoImages": WarpedBundleVideoImages,
    "WarpedRsmBundleAllVideoImages": WarpedRsmBundleAllVideoImages,
    "WarpedImageNoiseAugmentation": WarpedImageNoiseAugmentation,
    "WarpedLeapfusionHunyuanI2V": WarpedLeapfusionHunyuanI2V,
    "WarpedSaveAnimatedPng": WarpedSaveAnimatedPng,
    "WarpedUpscaleWithModel": WarpedUpscaleWithModel,
    # "WarpedBundleVideoImages": WarpedBundleVideoImages,
    "WarpedLoadVideosBatch": WarpedLoadVideosBatch,
    "WarpedWanImageToVideo": WarpedWanImageToVideo,
    # "WarpedImageFromBatch": WarpedImageFromBatch,
    "WarpedTeaCache": WarpedTeaCache,
    "WarpedWanLoadAndEditLoraBlocks": WarpedWanLoadAndEditLoraBlocks,
    # "WarpedWanBasicScheduler": WarpedWanBasicScheduler,
    # "WarpedHunyuanImageToVideo": WarpedHunyuanImageToVideo,
    "WarpedImageResize": WarpedImageResize,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "WarpedHunyuanMultiLoraMerge": "Warped Hunyuan Multi Lora Merge",
    "WarpedHunyuanMultiLoraAvgMerge": "Warped Hunyuan Multi Lora Avg Merge",
    "WarpedHunyuanLoraMerge": "Warped Hunyuan Lora Merge",
    # "WarpedHunyuanLoraMergeExp": "Warped Hunyuan Lora Merge Exp",
    # "WarpedHunyuanConvert32To64Exp": "Warped Hunyuan Convert 32 To 64 Exp",
    "WarpedHunyuanLoraAvgMerge": "Warped Hunyuan Lora Avg Merge",
    "WarpedWanLoraMerge": "Warped Wan Lora Merge",
    "WarpedSamplerCustomAdv": "Warped Sampler Custom Advanced (Image)",
    "WarpedSamplerCustomAdvLatent": "Warped Sampler Custom Advanced (Latent)",
    "WarpedCreateSpecialImageBatch": "Warped Create Special Image Batch",
    # "WarpedCreateSpecialImageBatchExt": "Warped Create Special Image Batch Ext",
    "WarpedCreateEmptyImageBatch": "Warped Create Empty Image Batch",
    "WarpedBundleVideoImages": "Warped Bundle Video Images",
    "WarpedRsmBundleAllVideoImages": "Warped Rsm Bundle All Video Images",
    "WarpedImageNoiseAugmentation": "Warped Image Noise Augmentation",
    "WarpedLeapfusionHunyuanI2V": "Warped Leapfusion Hunyuan I2V",
    "WarpedSaveAnimatedPng": "Warped Save Animated Png",
    "WarpedUpscaleWithModel": "Warped Upscale With Model",
    # "WarpedBundleVideoImages": "Warped Bundle Video Images",
    "WarpedLoadVideosBatch": "Warped Load Videos Batch",
    "WarpedWanImageToVideo": "Warped Wan Image To Video",
    # "WarpedImageFromBatch": "Warped Image From Batch",
    "WarpedTeaCache": "Warped TeaCache",
    "WarpedWanLoadAndEditLoraBlocks": "Warped Wan Load And Edit Lora Blocks",
    # "WarpedWanBasicScheduler": "Warped Wan Basic Scheduler",
    # "WarpedHunyuanImageToVideo": "Warped Hunyuan Image To Video",
    "WarpedImageResize": "Warped Image Resize",
}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
