from .nodes import *

NODE_CLASS_MAPPINGS = {
    "WarpedHunyuanMultiLoraMerge": WarpedHunyuanMultiLoraMerge,
    "WarpedHunyuanMultiLoraAvgMerge": WarpedHunyuanMultiLoraAvgMerge,
    "WarpedHunyuanLoraMerge": WarpedHunyuanLoraMerge,
    "WarpedHunyuanMultiLoraMixer": WarpedHunyuanMultiLoraMixer,
    "WarpedHunyuanMultiLoraMixerExt": WarpedHunyuanMultiLoraMixerExt,
    "WarpedHunyuanLoraAvgMerge": WarpedHunyuanLoraAvgMerge,
    "WarpedHunyuanLoraBatchMerge": WarpedHunyuanLoraBatchMerge,
    "WarpedWanLoraMerge": WarpedWanLoraMerge,
    "WarpedSamplerCustomAdv": WarpedSamplerCustomAdv,
    "WarpedSamplerCustomAdvLatent": WarpedSamplerCustomAdvLatent,
    "WarpedFramepackSampler": WarpedFramepackSampler,
    "WarpedCreateSpecialImageBatch": WarpedCreateSpecialImageBatch,
    "WarpedCreateEmptyImageBatch": WarpedCreateEmptyImageBatch,
    "WarpedCreateEmptyLatentBatch": WarpedCreateEmptyLatentBatch,
    "WarpedBundleVideoImages": WarpedBundleVideoImages,
    "WarpedBundleAllVideoImages": WarpedBundleAllVideoImages,
    # "WarpedBundleVideoImagesFramepack": WarpedBundleVideoImagesFramepack,
    "WarpedImageNoiseAugmentation": WarpedImageNoiseAugmentation,
    "WarpedLeapfusionHunyuanI2V": WarpedLeapfusionHunyuanI2V,
    "WarpedSaveAnimatedPng": WarpedSaveAnimatedPng,
    "WarpedUpscaleWithModel": WarpedUpscaleWithModel,
    "WarpedLoadVideosBatch": WarpedLoadVideosBatch,
    "WarpedWanImageToVideo": WarpedWanImageToVideo,
    "WarpedTeaCache": WarpedTeaCache,
    "WarpedWanLoadAndEditLoraBlocks": WarpedWanLoadAndEditLoraBlocks,
    "WarpedImageResize": WarpedImageResize,
    "WarpedImageResizeKJStyle": WarpedImageResizeKJStyle,
    "WarpedImageScaleToSide": WarpedImageScaleToSide,
    "WarpedLoadLorasBatchByPrefix": WarpedLoadLorasBatchByPrefix,
    "WarpedHunyuanVideoLoraLoader": WarpedHunyuanVideoLoraLoader,
    "WarpedHunyuanMultiLoraLoader": WarpedHunyuanMultiLoraLoader,
    "WarpedHunyuanLoraConvertKeys": WarpedHunyuanLoraConvertKeys,
    "WarpedLoraKeysAndMetadataReader": WarpedLoraKeysAndMetadataReader,
    "WarpedHunyuanLoraConvert": WarpedHunyuanLoraConvert,
    "WarpedFramepackLoraSelectBatch": WarpedFramepackLoraSelectBatch,
    "WarpedFramepackMultiLoraSelect": WarpedFramepackMultiLoraSelect,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    "WarpedHunyuanMultiLoraMerge": "Warped Hunyuan Multi Lora Merge",
    "WarpedHunyuanMultiLoraAvgMerge": "Warped Hunyuan Multi Lora Avg Merge",
    "WarpedHunyuanLoraMerge": "Warped Hunyuan Lora Merge",
    "WarpedHunyuanMultiLoraMixer": "Warped Hunyuan Multi Lora Mixer",
    "WarpedHunyuanMultiLoraMixerExt": "Warped Hunyuan Multi Lora Mixer Ext",
    "WarpedHunyuanLoraAvgMerge": "Warped Hunyuan Lora Avg Merge",
    "WarpedHunyuanLoraBatchMerge": "Warped Hunyuan Lora Batch Merge",
    "WarpedWanLoraMerge": "Warped Wan Lora Merge",
    "WarpedSamplerCustomAdv": "Warped Sampler Custom Advanced (Image)",
    "WarpedSamplerCustomAdvLatent": "Warped Sampler Custom Advanced (Latent)",
    "WarpedFramepackSampler": "Warped Framepack Sampler",
    "WarpedCreateSpecialImageBatch": "Warped Create Special Image Batch",
    "WarpedCreateEmptyImageBatch": "Warped Create Empty Image Batch",
    "WarpedCreateEmptyLatentBatch": "Warped Create Empty Latent Batch",
    "WarpedBundleVideoImages": "Warped Bundle Video Images",
    "WarpedBundleAllVideoImages": "Warped Bundle All Video Images",
    # "WarpedBundleVideoImagesFramepack": "Warped Bundle Video Images Framepack",
    "WarpedImageNoiseAugmentation": "Warped Image Noise Augmentation",
    "WarpedLeapfusionHunyuanI2V": "Warped Leapfusion Hunyuan I2V",
    "WarpedSaveAnimatedPng": "Warped Save Animated Png",
    "WarpedUpscaleWithModel": "Warped Upscale With Model",
    "WarpedLoadVideosBatch": "Warped Load Videos Batch",
    "WarpedWanImageToVideo": "Warped Wan Image To Video",
    "WarpedTeaCache": "Warped TeaCache",
    "WarpedWanLoadAndEditLoraBlocks": "Warped Wan Load And Edit Lora Blocks",
    "WarpedImageResize": "Warped Image Resize",
    "WarpedImageResizeKJStyle": "Warped Image Resize KJ Style",
    "WarpedImageScaleToSide": "Warped Image Scale To Side",
    "WarpedLoadLorasBatchByPrefix": "Warped Load Loras Batch By Prefix",
    "WarpedHunyuanVideoLoraLoader": "Warped Hunyuan Video Lora Loader",
    "WarpedHunyuanMultiLoraLoader": "Warped Hunyuan Video Multi Lora Loader",
    "WarpedHunyuanLoraConvertKeys": "Warped Hunyuan Lora Convert Keys",
    "WarpedLoraKeysAndMetadataReader": "Warped Lora Keys And Metadata Reader",
    "WarpedHunyuanLoraConvert": "Warped Hunyuan Lora Convert",
    "WarpedFramepackLoraSelectBatch": "Warped Framepack Lora Select Batch",
    "WarpedFramepackMultiLoraSelect": "Warped Framepack Multi Lora Select",
}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
